/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.votingsystem.view;

import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import lk.ijse.votingsystem.controller.CandidateController;
import lk.ijse.votingsystem.controller.VoterController;
import lk.ijse.votingsystem.dto.CandidateDTO;
import lk.ijse.votingsystem.observer.Observerr;

/**
 *
 * @author HP
 */
public class CandidateDetail extends javax.swing.JInternalFrame implements Observerr{

    /**
     * Creates new form CandidateDetail
     */
//    public CandidateDetail() {
//        initComponents();
//        allCndidates();
//    }
    private JPanel pnlIntern;
    CandidateDetail(JPanel pnlJPanel) {
        initComponents();
        allCndidates();
        pnlIntern=pnlJPanel;
        try {
           UnicastRemoteObject.exportObject(this, 0);
           CandidateController.getSubject().registerObserver(this);
           CandidateController.getSubject().notifyObservers();
        } catch (Exception ex) {
            Logger.getLogger(CandidateDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCandidate = new org.jdesktop.swingx.JXTable();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setText("Candidate Details");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jXPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 460, 60));

        tblCandidate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Candidate No.", "Full Name", "NIC No.", "Designation"
            }
        ));
        jScrollPane1.setViewportView(tblCandidate);

        jXPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 940, 240));

        jXLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jXLabel2.setText("* If you want to search candidates by name you can saw from press \"Search Candidates\" button.");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel1.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 890, 30));

        jXLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jXLabel3.setText("* If you want to see candidate more details you can saw from press \"See more\" button.");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel1.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 890, 30));

        jXLabel4.setBackground(new java.awt.Color(51, 204, 0));
        jXLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/searchCandidate.png"))); // NOI18N
        jXLabel4.setText(" Search Candidates");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXLabel4.setOpaque(true);
        jXPanel1.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 230, 40));

        jXLabel5.setBackground(new java.awt.Color(51, 204, 0));
        jXLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/SeeMore.png"))); // NOI18N
        jXLabel5.setText("   See more ");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXLabel5.setOpaque(true);
        jXLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXLabel5MousePressed(evt);
            }
        });
        jXPanel1.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 210, 40));

        jXLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXPanel1.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1030, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel5MousePressed
       DefaultTableModel dtm=(DefaultTableModel) tblCandidate.getModel();
       int i=tblCandidate.getSelectedRow();
       String cId=(String) tblCandidate.getValueAt(i,0);
       SeemoreCandidate sc=new SeemoreCandidate(pnlIntern,cId);
       pnlIntern.removeAll();
       pnlIntern.add(sc);
       sc.setVisible(true);
        
    }//GEN-LAST:event_jXLabel5MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXTable tblCandidate;
    // End of variables declaration//GEN-END:variables

    private void allCndidates() {
        try {
            DefaultTableModel dtm=(DefaultTableModel) tblCandidate.getModel();
            dtm.setRowCount(0);
            List<CandidateDTO> getAllCandidates=CandidateController.getAllCandidates();
            if(getAllCandidates==null){
                return;
            }
            for (CandidateDTO allCandidate : getAllCandidates) {
                Object[] rowData={allCandidate.getcId(),allCandidate.getName(),allCandidate.getNic(),allCandidate.getPost()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(CandidateDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void updateObservers() throws Exception {
        allCndidates();
        System.out.println("yyyyyyyyyyyyyyyyyy");
    }
}
