/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.votingsystem.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import lk.ijse.votingsystem.controller.CandidateController;

/**
 *
 * @author HP
 */
public class CommisonerHome extends javax.swing.JFrame {
    
    /**
     * Creates new form Home
     */
    private String comId;
    public CommisonerHome() {
        initComponents();
        setDate();
        setTime();
    }

    CommisonerHome(String cmId) {
         initComponents();
        setDate();
        setTime();
        this.comId=cmId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        lblDate = new org.jdesktop.swingx.JXLabel();
        lblTime = new org.jdesktop.swingx.JXLabel();
        jXPanel4 = new org.jdesktop.swingx.JXPanel();
        pnlIntern = new org.jdesktop.swingx.JXPanel();
        jXPanel5 = new org.jdesktop.swingx.JXPanel();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jXPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jXPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jXPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel8.setText("Comission");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel3.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 130, 30));

        jXLabel7.setText("Mannage election");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel3.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 180, 30));

        jXPanel1.add(jXPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 0, 630));

        jXPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jXPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jXLabel1.setText("UCSC Voting System");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jXPanel2.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 560, 65));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jXPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 280, 41));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jXPanel2.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 80, 224, 41));

        jXPanel1.add(jXPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 150));

        jXPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlInternLayout = new javax.swing.GroupLayout(pnlIntern);
        pnlIntern.setLayout(pnlInternLayout);
        pnlInternLayout.setHorizontalGroup(
            pnlInternLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        pnlInternLayout.setVerticalGroup(
            pnlInternLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jXPanel4.add(pnlIntern, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 1100, 620));

        jXPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jXPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jXPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jXLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jXLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/voter.png"))); // NOI18N
        jXLabel10.setText("Manage Voters");
        jXLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXLabel10.setOpaque(true);
        jXLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXLabel10MousePressed(evt);
            }
        });
        jXPanel5.add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 60));

        jXLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jXLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jXLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/view.png"))); // NOI18N
        jXLabel4.setText("Manage Election");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXLabel4.setOpaque(true);
        jXLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXLabel4MousePressed(evt);
            }
        });
        jXPanel5.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 60));

        jXLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jXLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jXLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/ManageCandidate.png"))); // NOI18N
        jXLabel13.setText("Manage Candidates");
        jXLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXLabel13.setOpaque(true);
        jXLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXLabel13MousePressed(evt);
            }
        });
        jXPanel5.add(jXLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 250, 60));

        jXLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel5.setText("Manage Commisional");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel5.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 200, 30));

        jXLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel9.setText("members");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel5.add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, -1));

        jXLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jXLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jXLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/comission.png"))); // NOI18N
        jXLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXLabel6.setOpaque(true);
        jXLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXLabel6MousePressed(evt);
            }
        });
        jXPanel5.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 250, 60));

        jXPanel4.add(jXPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 270, 620));

        jXPanel1.add(jXPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1370, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel10MousePressed
        ManageVoters v1=new ManageVoters(pnlIntern);
        pnlIntern.removeAll();
        pnlIntern.add(v1);
        v1.setVisible(true);
    }//GEN-LAST:event_jXLabel10MousePressed

    private void jXLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel4MousePressed
        ManageVoteDetail mv=new ManageVoteDetail();
        pnlIntern.removeAll();
        pnlIntern.add(mv);
        mv.setVisible(true);
    }//GEN-LAST:event_jXLabel4MousePressed

    private void jXLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel6MousePressed
        ManageCommission cm=new ManageCommission(pnlIntern);
        pnlIntern.removeAll();
        pnlIntern.add(cm);
        cm.setVisible(true);
    }//GEN-LAST:event_jXLabel6MousePressed

    private void jXLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel13MousePressed
        ManageCandidate c1=new ManageCandidate(pnlIntern);
        pnlIntern.removeAll();
        pnlIntern.add(c1);
        c1.setVisible(true);
    }//GEN-LAST:event_jXLabel13MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommisonerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommisonerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommisonerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommisonerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommisonerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXPanel jXPanel4;
    private org.jdesktop.swingx.JXPanel jXPanel5;
    private org.jdesktop.swingx.JXLabel lblDate;
    private org.jdesktop.swingx.JXLabel lblTime;
    private org.jdesktop.swingx.JXPanel pnlIntern;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String date = df.format(d1);
        lblDate.setText(date);


    }

    private void setTime() {
         new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date d1 = new Date();
                    String time = new SimpleDateFormat("hh:mm:ss aa").format(d1);
                    lblTime.setText(time);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(NewLog.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
}
