/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.votingsystem.view;

import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class Home extends javax.swing.JFrame {
  
    /**
     * Creates new form Home
     */
//    voteDetail v;
//    CandidateDetail cd;
//    UploadCandidate c1;
//    BallotPaper bp;
//    Result r;
    public Home() {
        initComponents();
//         v=new voteDetail();
//         cd=new CandidateDetail(pnlPanl);
//          c1 =new UploadCandidate();
//         bp =new BallotPaper();
//         r=new Result();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel10MousePressed
        voteDetail v=new voteDetail();
        pnlPanl.removeAll();
        pnlPanl.add(v);
//        cd.dispose();
//        c1.dispose();
//        bp.dispose();
//        r.dispose();
        v.setVisible(true);
        
    }//GEN-LAST:event_jXLabel10MousePressed

    private void jXLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel4MousePressed
        CandidateDetail cd=new CandidateDetail(pnlPanl);
        pnlPanl.removeAll();
        pnlPanl.add(cd);
//        v.dispose();
//        c1.dispose();
//        bp.dispose();
//        r.dispose();
        cd.setVisible(true);
        
    }//GEN-LAST:event_jXLabel4MousePressed

    private void jXLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel5MousePressed
       UploadCandidate c1=new UploadCandidate();
        c1=new UploadCandidate();
       pnlPanl.removeAll();
       pnlPanl.add(c1);
//       v.dispose();
//        cd.dispose();
//        bp.dispose();
//        r.dispose();
       c1.setVisible(true);
    }//GEN-LAST:event_jXLabel5MousePressed

    private void jXLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel14MousePressed
        Result r=new Result();
        r=new Result();
        pnlPanl.removeAll();
        pnlPanl.add(r);
//        v.dispose();
//        c1.dispose();
//        cd.dispose();
//        bp.dispose();
        r.setVisible(true);
    }//GEN-LAST:event_jXLabel14MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
