/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.votingsystem.view;

import com.sun.deploy.uitoolkit.impl.fx.ui.FXUIFactory;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.votingsystem.controller.ElectionController;
import lk.ijse.votingsystem.dto.AllElectionDTO;
import lk.ijse.votingsystem.dto.CommissionDTO;
import lk.ijse.votingsystem.dto.ElectionDTO;
import lk.ijse.votingsystem.dto.ElectionDetailDTO;
import lk.ijse.votingsystem.dto.ElectionDetail_PKDTO;

/**
 *
 * @author HP
 */
public class ManageVoteDetail extends javax.swing.JInternalFrame {

    private String eId;
    private String eYear;
    private static String startTime;
    private static String eTime;
    private static String starPeriod;
    private static String ePeriod;
    private static String timePeriod;

    /**
     * Creates new form ManageVoteDetail
     */
    public ManageVoteDetail() {
        initComponents();
        setDate();
        getDetail();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        txtToday = new org.jdesktop.swingx.JXTextField();
        txtcmId = new org.jdesktop.swingx.JXTextField();
        btnUpdate = new org.jdesktop.swingx.JXButton();
        btnSet = new org.jdesktop.swingx.JXButton();
        txtEleId = new org.jdesktop.swingx.JXTextField();
        txtTimePeriod = new org.jdesktop.swingx.JXTextField();
        txtenue = new org.jdesktop.swingx.JXTextField();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        cmbEnd = new org.jdesktop.swingx.JXComboBox();
        cmbEndTime = new org.jdesktop.swingx.JXComboBox();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new org.jdesktop.swingx.JXTextArea();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        txtElectionYear = new org.jdesktop.swingx.JXTextField();
        txtDate = new org.jdesktop.swingx.JXTextField();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel2.setText("Upload Election Details");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        getContentPane().add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 580, 70));

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtToday.setEditable(false);
        jXPanel1.add(txtToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 160, 30));
        jXPanel1.add(txtcmId, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 160, 30));

        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/update.png"))); // NOI18N
        btnUpdate.setText("Update Election Detail");
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jXPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 270, 40));

        btnSet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/set.png"))); // NOI18N
        btnSet.setText("Set Election Detail");
        btnSet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });
        jXPanel1.add(btnSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 240, 40));
        jXPanel1.add(txtEleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 200, 30));
        jXPanel1.add(txtTimePeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 170, 30));
        jXPanel1.add(txtenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 200, 30));

        jXLabel9.setText("Description");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 100, 30));

        jXLabel6.setText("Time Period");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 90, 30));

        jXLabel8.setText("Ending Time");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 90, 30));

        jXLabel7.setText("Election ID");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 110, 30));

        cmbEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "am", "pm" }));
        cmbEnd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEndActionPerformed(evt);
            }
        });
        jXPanel1.add(cmbEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 70, 30));

        cmbEndTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbEndTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEndTimeActionPerformed(evt);
            }
        });
        jXPanel1.add(cmbEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 90, 30));

        jXLabel5.setText("Election Date");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 30));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        jXPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 280, 80));

        jXLabel11.setText("Venue");
        jXLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 100, 30));

        jLabel5.setText("(YYYY-MM-DD)");
        jXPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 90, 20));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));
        jXPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 60, 30));

        jXLabel13.setText("Election Year");
        jXLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 90, 30));

        jXLabel12.setText("Starting Time");
        jXLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 110, 30));
        jXPanel1.add(txtElectionYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 200, 30));
        jXPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 200, 30));

        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1020, 490));

        jXLabel3.setText("Comissioner ID");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 100, 30));

        jXLabel4.setText("Date");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 90, 30));

        jXLabel10.setText("jXLabel10");
        jXPanel1.add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        getContentPane().add(jXPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1080, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        try {
            int t1 = 0;
            int t2 = 0;
            String eId = txtEleId.getText();
            String eYear = txtElectionYear.getText();
            String eDate = txtDate.getText();
            String s1 = (String) cmbStrartTime.getSelectedItem();
            String s2 = (String) cmbStart.getSelectedItem();
            String startTime = s1 + "-" + s2;
            String e1 = (String) cmbEndTime.getSelectedItem();
            String e2 = (String) cmbEnd.getSelectedItem();
            String endTime = e1 + "-" + e2;
            String venue = txtenue.getText();
            String desc = txtDesc.getText();
            String usr = txtcmId.getText();
            String date = txtToday.getText();
            this.eId = eId;
            this.eYear = eYear;
            this.startTime = s1;
            this.eTime = e1;
            this.ePeriod = e2;
            this.starPeriod = s2;
            if (s2.equals("pm")) {
                t1 = Integer.parseInt(s1) + 12;
            } else {
                t1 = Integer.parseInt(s1);
            }
            if (e2.equals("pm")) {
                t2 = Integer.parseInt(e1) + 12;
            } else {
                t2 = Integer.parseInt(e1);
            }
            int period = t2 - t1;
            this.ePeriod = period + " :hr";
            CommissionDTO commissionDTO = new CommissionDTO();
            commissionDTO.setCmId(usr);

            ElectionDTO electionDTO = new ElectionDTO();
            electionDTO.seteId(eId);
            electionDTO.setElectionYear(eYear);
            ElectionDetailDTO eddto = new ElectionDetailDTO();

            eddto.setCommissionDTO(commissionDTO);
            eddto.setElectionDTO(electionDTO);
            eddto.setDate(date);
            eddto.setDescription(desc);
            eddto.setElectionDate(eDate);
            eddto.setEndTime(endTime);
            eddto.setPlace(venue);
            eddto.setStartTime(startTime);

            ElectionDetail_PKDTO electionDetail_PKDTO = new ElectionDetail_PKDTO(commissionDTO.getCmId(), eId);
            AllElectionDTO allElectionDTO = new AllElectionDTO();
            allElectionDTO.setElectionDTO(electionDTO);
            allElectionDTO.setElectionDetailDTO(eddto);
            allElectionDTO.setCommissionDTO(commissionDTO);
            boolean add = ElectionController.addElection(allElectionDTO);
            if (add) {
                JOptionPane.showMessageDialog(this, "Added Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Added Failled");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageVoteDetail.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSetActionPerformed

    private void cmbEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEndTimeActionPerformed
//       int t1;
//       int t2;
//        if(cmbEnd.getSelectedItem().equals("pm")){
//            String t=(String) cmbEndTime.getSelectedItem();
//            t1=Integer.parseInt(t)+12;
//        }else{
//            String t=(String) cmbEndTime.getSelectedItem();
//            t1=Integer.parseInt(t);
//        }
//        if(cmbStart.getSelectedItem().equals("pm")){
//           String t=(String) cmbStrartTime.getSelectedItem();
//            t2=Integer.parseInt(t)+12;
//        }else{
//            String t=(String) cmbStrartTime.getSelectedItem();
//            t2=Integer.parseInt(t);
//        }
//        int tPeriod=t2-t1;
//        txtTimePeriod.setText(tPeriod+" :hr");
        eTime = (String) cmbEndTime.getSelectedItem();

    }//GEN-LAST:event_cmbEndTimeActionPerformed

    private void cmbEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEndActionPerformed
        ePeriod = (String) cmbEnd.getSelectedItem();
    }//GEN-LAST:event_cmbEndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnSet;
    private org.jdesktop.swingx.JXButton btnUpdate;
    private org.jdesktop.swingx.JXComboBox cmbEnd;
    private org.jdesktop.swingx.JXComboBox cmbEndTime;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXTextField txtDate;
    private org.jdesktop.swingx.JXTextArea txtDesc;
    private org.jdesktop.swingx.JXTextField txtEleId;
    private org.jdesktop.swingx.JXTextField txtElectionYear;
    private org.jdesktop.swingx.JXTextField txtTimePeriod;
    private org.jdesktop.swingx.JXTextField txtToday;
    private org.jdesktop.swingx.JXTextField txtcmId;
    private org.jdesktop.swingx.JXTextField txtenue;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String date = df.format(d1);
        txtToday.setText(date);
    }

    private void getDetail() {
        try {
            List<ElectionDetailDTO> getDeail = ElectionController.getAll();
            for (ElectionDetailDTO electionDetailDTO : getDeail) {
//                txtEleId.setText(electionDetailDTO.getElectionDetail_PKDTO().geteId());

                txtDate.setText(electionDetailDTO.getElectionDate());
                txtDesc.setText(electionDetailDTO.getDescription());
                txtenue.setText(electionDetailDTO.getPlace());
               txtEleId.setText(electionDetailDTO.getElectionDTO().geteId());
                String startTime = electionDetailDTO.getStartTime();
//                String[] part=startTime.split("-",2);
//                String cmbs1=part[0];
//                String cmbs2=part[1];
               
                String[] part = startTime.split("-", 2);
                String cmbs1 = part[0];
                String cmbs2 = part[1];
                System.out.println(cmbs1);
                System.out.println(cmbs2);
//                cmbStrartTime.setSelectedItem(cmbs1);
//                cmbStart.setSelectedItem(cmbs2);
                
                
                String[] part1=electionDetailDTO.getEndTime().split("-",2);
                String cmbe1 = part1[0];
                String cmbe2 = part1[1];
                System.out.println(cmbe1);
                System.out.println(cmbe2);
//                cmbStrartTime.setSelectedItem(cmbs1);
//                cmbStart.setSelectedItem(cmbs2);
                
                
              
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageVoteDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
