/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.votingsystem.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lk.ijse.votingsystem.controller.CommissionController;
import lk.ijse.votingsystem.dto.CommissionDTO;
import org.jdesktop.swingx.JXPanel;

/**
 *
 * @author HP
 */
public class ManageCommission extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManageCommission
     */
    private JPanel pnlView;
    private static int cm=1;
    ManageCommission(JXPanel pnlIntern) {
        initComponents();
        pnlView=pnlIntern;
        loadCommissionId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        txtName = new org.jdesktop.swingx.JXTextField();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        txtNic = new org.jdesktop.swingx.JXTextField();
        txtTele = new org.jdesktop.swingx.JXTextField();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        txtUserName = new org.jdesktop.swingx.JXTextField();
        btnSearch = new org.jdesktop.swingx.JXButton();
        btnDelete = new org.jdesktop.swingx.JXButton();
        txtBirth = new org.jdesktop.swingx.JXTextField();
        btnAdd = new org.jdesktop.swingx.JXButton();
        btnView = new org.jdesktop.swingx.JXButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new org.jdesktop.swingx.JXTextArea();
        txtCmid = new org.jdesktop.swingx.JXTextField();
        btnUpdate = new org.jdesktop.swingx.JXButton();
        txtPwrd = new javax.swing.JPasswordField();
        btnSearch1 = new org.jdesktop.swingx.JXButton();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel2.setText("Manage Commissional Members");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jXPanel1.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 810, 60));

        jXLabel3.setText("Telephone No.");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 140, 30));

        jXLabel4.setText("Date of Birth");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 100, 30));

        jXLabel8.setText("NIC No.");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, 30));

        jXLabel7.setText("Name with Initials");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jXPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 270, 30));

        jXLabel10.setText("User Name");
        jXLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 80, 30));

        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        jXPanel1.add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 160, 30));

        txtTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleActionPerformed(evt);
            }
        });
        jXPanel1.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 160, 30));

        jXLabel9.setText("Password");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 100, 30));

        jXLabel6.setText("Postal Address");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 110, 30));

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        jXPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 160, 30));

        btnSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jXPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 130, 40));

        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jXPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 150, 40));

        txtBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthActionPerformed(evt);
            }
        });
        jXPanel1.add(txtBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 160, 30));

        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/add.png"))); // NOI18N
        btnAdd.setText("Create New");
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jXPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 180, 40));

        btnView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/view.png"))); // NOI18N
        btnView.setText("Show All");
        btnView.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jXPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 160, 40));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jXPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 260, 100));

        txtCmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmidActionPerformed(evt);
            }
        });
        jXPanel1.add(txtCmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 150, 30));

        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jXPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 160, 40));
        jXPanel1.add(txtPwrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 160, 30));

        btnSearch1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/Refresh (2).png"))); // NOI18N
        btnSearch1.setText("Refresh");
        btnSearch1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearch1MousePressed(evt);
            }
        });
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jXPanel1.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 40));

        jXLabel5.setText("Commissioner ID");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, 30));

        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1030, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleActionPerformed

    private void txtCmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCmidActionPerformed

    private void txtBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            CommissionDTO dto=CommissionController.findCommissioner(txtCmid.getText());
            CommissionDTO commissionDTO = new CommissionDTO(txtCmid.getText(), txtName.getText(), txtNic.getText(), txtTele.getText(), txtAddress.getText(), dto.getUserName(),dto.getPassword());
            
            int x = JOptionPane.showConfirmDialog(this, "Are you sure update?");
            if (x == 0) {
                try {
                    boolean updated = CommissionController.updateCommissioner(commissionDTO);
                    if (updated) {
                        JOptionPane.showMessageDialog(this, "Updated...");
                    } else {
                        JOptionPane.showMessageDialog(this, "Update Failled");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(ManageCommission.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageCommission.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int x=JOptionPane.showConfirmDialog(this,"Are you sure delete this commissioner?");
        if(x==0){
            try {
                boolean delete=CommissionController.deleteCommissioner(txtCmid.getText());
                if(delete){
                    JOptionPane.showMessageDialog(this,"Deleted Successfully");
                }else{
                    JOptionPane.showMessageDialog(this,"Deleted...");
                }
            } catch (Exception ex) {
                Logger.getLogger(ManageCommission.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String cmId = txtCmid.getText();
            String name = txtName.getText();
            String nic = txtNic.getText();
            String tpNo = txtTele.getText();
            String address = txtAddress.getText();
            String userName = txtUserName.getText();
            String password = txtPwrd.getText();

            CommissionDTO commissionDTO = new CommissionDTO(cmId, name, nic, tpNo, address, userName, password);
            boolean isAdd = CommissionController.addCommioner(commissionDTO);
            if (isAdd) {
                int x = JOptionPane.showConfirmDialog(this, "Are you sure added this member?");
                if (x == 0) {
                    JOptionPane.showMessageDialog(this, "Added Successfully");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Added Failled");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageCommission.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            CommissionDTO commissionDTO = CommissionController.findCommissioner(txtCmid.getText());
            if (commissionDTO != null) {
                txtName.setText(commissionDTO.getName());
                txtNic.setText(commissionDTO.getNic());
                txtTele.setText(commissionDTO.getTpNo());
                txtAddress.setText(commissionDTO.getAddress());
            } else {
                JOptionPane.showMessageDialog(this, "Not such commissioner member");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageCommission.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        txtCmid.setText("");
        txtName.setText("");
        txtNic.setText("");
        txtAddress.setText("");
        txtBirth.setText("");
        txtPwrd.setText("");
        txtTele.setText("");
        txtUserName.setText("");
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnSearch1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch1MousePressed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        ViewCommissioner viewCommissioner=new ViewCommissioner(pnlView);
        pnlView.removeAll();
        pnlView.add(viewCommissioner);
        viewCommissioner.setVisible(true);
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnAdd;
    private org.jdesktop.swingx.JXButton btnDelete;
    private org.jdesktop.swingx.JXButton btnSearch;
    private org.jdesktop.swingx.JXButton btnSearch1;
    private org.jdesktop.swingx.JXButton btnUpdate;
    private org.jdesktop.swingx.JXButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXTextArea txtAddress;
    private org.jdesktop.swingx.JXTextField txtBirth;
    private org.jdesktop.swingx.JXTextField txtCmid;
    private org.jdesktop.swingx.JXTextField txtName;
    private org.jdesktop.swingx.JXTextField txtNic;
    private javax.swing.JPasswordField txtPwrd;
    private org.jdesktop.swingx.JXTextField txtTele;
    private org.jdesktop.swingx.JXTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void loadCommissionId() {
        txtCmid.setText("CM"+cm);
    }
}
