/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.votingsystem.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.votingsystem.controller.CommissionController;
import lk.ijse.votingsystem.dto.CommissionDTO;

/**
 *
 * @author HP
 */
public class NewLog extends javax.swing.JFrame {
    private String cmId;
    /**
     * Creates new form NewLog
     */
    
    public NewLog() {
        initComponents();
        setLocationRelativeTo(null);
        
        setDate();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel15 = new org.jdesktop.swingx.JXLabel();
        txtTime = new org.jdesktop.swingx.JXLabel();
        jXLabel16 = new org.jdesktop.swingx.JXLabel();
        txtDate = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        txtUname = new org.jdesktop.swingx.JXTextField();
        txtPwrd = new javax.swing.JPasswordField();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();

        jXPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel15.setText("Welcome");
        jXLabel15.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jXPanel1.add(jXLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 40));

        txtTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jXPanel1.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 210, 40));

        jXLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jXLabel16.setText("UCSC Voting System");
        jXLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jXPanel1.add(jXLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 390, 40));

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jXPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 280, 40));

        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jXPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 110));

        jXLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/loginimage.jpg"))); // NOI18N
        jXPanel1.add(jXLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 500, 390));

        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });
        jXPanel1.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 160, 30));

        txtPwrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwrdActionPerformed(evt);
            }
        });
        jXPanel1.add(txtPwrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 160, 30));

        jXLabel8.setText("User Name");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jXPanel1.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 90, 30));

        jXLabel9.setBackground(new java.awt.Color(51, 102, 255));
        jXLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel9.setText("       LogIn");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXLabel9.setOpaque(true);
        jXLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXLabel9MousePressed(evt);
            }
        });
        jXPanel1.add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 140, 40));

        jXLabel4.setBackground(new java.awt.Color(153, 204, 255));
        jXLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jXLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel4.setText("      Ballot Paper");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jXLabel4.setOpaque(true);
        jXLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXLabel4MousePressed(evt);
            }
        });
        jXPanel1.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 320, 50));

        jXLabel6.setText("Commision LogIn");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jXPanel1.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 220, 30));

        jXLabel7.setText("Password");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jXPanel1.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 90, 30));

        jXLabel3.setBackground(new java.awt.Color(153, 204, 255));
        jXLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jXLabel3.setForeground(new java.awt.Color(153, 204, 255));
        jXLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jXLabel3.setOpaque(true);
        jXPanel1.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 320, 240));

        jXLabel5.setBackground(new java.awt.Color(153, 204, 255));
        jXLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jXLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel5.setText("          Log In");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jXLabel5.setOpaque(true);
        jXLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXLabel5MousePressed(evt);
            }
        });
        jXPanel1.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 320, 50));

        jXLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jXPanel1.add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 370, 390));
        jXPanel1.add(jXLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 500, 400));

        jXLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXLabel2.setForeground(new java.awt.Color(153, 204, 255));
        jXLabel2.setOpaque(true);
        jXPanel1.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 900, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void txtPwrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPwrdActionPerformed

    private void jXLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel4MousePressed
        LogInBallot lb=new LogInBallot();
       lb.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jXLabel4MousePressed

    private void jXLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel9MousePressed
        try {
            List<CommissionDTO> getAll = CommissionController.getAllMembers();
            String user = txtUname.getText();
            String perd = txtPwrd.getText();
            int count = 0;
            if (getAll != null) {
                for (CommissionDTO commissionDTO : getAll) {
                    if (commissionDTO != null) {
                        String userName = commissionDTO.getUserName();
                        System.out.println("cc" + commissionDTO.getUserName());
                        if (userName.equals(user)) {
                            cmId=commissionDTO.getCmId();
                            try {
                                CommissionDTO dto = CommissionController.findCommissioner(commissionDTO.getCmId());
                                if (perd.equals(dto.getPassword())) {
                                    CommisonerHome ch=new CommisonerHome(cmId);
                                    ch.setVisible(true);
                                    this.dispose();
                                } else {
                                    JOptionPane.showMessageDialog(this, "Password is incorrect. Try again..");
                                }
                            } catch (Exception ex) {
                                Logger.getLogger(NewLog.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Wrong user. Can't LogIn");
                        }
                    }
                }
            }else{
                System.out.println("get All null");
            }
        } catch (Exception ex) {
            Logger.getLogger(NewLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXLabel9MousePressed

    private void jXLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel5MousePressed
         Home h1 = new Home();
        h1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jXLabel5MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel15;
    private org.jdesktop.swingx.JXLabel jXLabel16;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXLabel txtDate;
    private javax.swing.JPasswordField txtPwrd;
    private org.jdesktop.swingx.JXLabel txtTime;
    private org.jdesktop.swingx.JXTextField txtUname;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String date = df.format(d1);
        txtDate.setText(date);
    }

    private void setTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date d1 = new Date();
                    String time = new SimpleDateFormat("hh:mm:ss aa").format(d1);
                    txtTime.setText(time);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(NewLog.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
}
