/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.votingsystem.view;

import com.sun.beans.util.Cache;
import java.awt.Image;
import java.io.FileOutputStream;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import lk.ijse.votingsystem.controller.CandidateController;
import lk.ijse.votingsystem.dto.CandidateDTO;

/**
 *
 * @author HP
 */
public class SeemoreCandidate extends javax.swing.JInternalFrame {

    /**
     * Creates new form SeemoreCandidate
     */
    private JPanel pnl;
    private String cId;

    public SeemoreCandidate(JPanel pnlIntern, String cId) {
        initComponents();
        pnl = pnlIntern;
        this.cId = cId;
        getAllCandidates();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        txtPost = new org.jdesktop.swingx.JXTextField();
        txtNic = new org.jdesktop.swingx.JXTextField();
        txtFullName = new org.jdesktop.swingx.JXTextField();
        txtCid = new org.jdesktop.swingx.JXTextField();
        lblPhoto = new org.jdesktop.swingx.JXLabel();
        lblDetail = new org.jdesktop.swingx.JXLabel();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setEnabled(false);
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setText("Full Name");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, 31));

        jXLabel2.setText("Candidate No.");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, 31));

        jXLabel3.setText("Post");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 70, 31));

        jXLabel4.setText("NIC No.");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 70, 31));

        txtPost.setEnabled(false);
        jXPanel1.add(txtPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 140, 30));

        txtNic.setEnabled(false);
        jXPanel1.add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, 30));

        txtFullName.setEnabled(false);
        jXPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 370, 30));

        txtCid.setEnabled(false);
        jXPanel1.add(txtCid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, 30));

        lblPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXPanel1.add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 220, 220));

        lblDetail.setText("detail,designation,service");
        jXPanel1.add(lblDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 860, 140));

        jXLabel9.setText("vision");
        jXPanel1.add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 180, 140));

        jXLabel8.setText("Vission -:");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 90, 30));

        jXLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXPanel1.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1010, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1084, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXLabel lblDetail;
    private org.jdesktop.swingx.JXLabel lblPhoto;
    private org.jdesktop.swingx.JXTextField txtCid;
    private org.jdesktop.swingx.JXTextField txtFullName;
    private org.jdesktop.swingx.JXTextField txtNic;
    private org.jdesktop.swingx.JXTextField txtPost;
    // End of variables declaration//GEN-END:variables

    private void getAllCandidates() {
        try {
            CandidateDTO candidateDTO = CandidateController.searchCandidate(cId);
            txtCid.setText(cId);
            txtFullName.setText(candidateDTO.getName());
            txtNic.setText(candidateDTO.getNic());
            txtPost.setText(candidateDTO.getPost());

            lblDetail.setText(candidateDTO.getDesignationDetail() + "/n" + candidateDTO.getServiceDetail() + "/n" + candidateDTO.getVisionDetail() + "/n" + candidateDTO.getOtherDetail());
            //byte[] image = candidateDTO.getImage();
            //String image1 = Arrays.toString(candidateDTO.getImage());
         //   String fileName=candidateDTO.getFileName();
//            ImageIcon image2 = new ImageIcon(fileName);
//            System.out.println("getfName"+fileName);
//            Image im = image2.getImage();
//            Image myImg=im.getScaledInstance(lblPhoto.getWidth(),lblPhoto.getHeight(),Image.SCALE_SMOOTH);
//            System.out.println("width"+lblPhoto.getWidth());
//            System.out.println("Hight"+lblPhoto.getHeight());
            
         //   ImageIcon newImage = new ImageIcon(myImg);
          //  lblPhoto.setIcon(newImage);
             CandidateDTO cd = CandidateController.searchCandidate(txtCid.getText());
            String image=cd.getFileName();

            ImageIcon imageIcon = new ImageIcon(image);
            lblPhoto.setIcon(imageIcon);
            

        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
            Logger.getLogger(SeemoreCandidate.class.getName()).log(Level.SEVERE, null, ex);

        } catch (Exception ex) {
            Logger.getLogger(SeemoreCandidate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
