/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.votingsystem.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.votingsystem.controller.CandidateController;
import lk.ijse.votingsystem.dto.CandidateDTO;

/**
 *
 * @author HP
 */
public class UploadCandidate extends javax.swing.JInternalFrame {

    /**
     * Creates new form UploadCandidate
     */
    public UploadCandidate() {
        initComponents();
        pnlVisible.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        txtIndex = new org.jdesktop.swingx.JXTextField();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        txtPwrd = new javax.swing.JPasswordField();
        pnlVisible = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetail = new org.jdesktop.swingx.JXTextArea();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtVission = new org.jdesktop.swingx.JXTextArea();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtService = new org.jdesktop.swingx.JXTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesignation = new org.jdesktop.swingx.JXTextArea();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        jButton1 = new javax.swing.JButton();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel6.setText("Password");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 100, 30));
        jXPanel1.add(txtIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 170, 30));

        jXLabel7.setText("Candidate University Index No.");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 200, 30));
        jXPanel1.add(txtPwrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 170, 30));

        txtDetail.setColumns(20);
        txtDetail.setRows(5);
        jScrollPane1.setViewportView(txtDetail);

        jXLabel4.setText("Other Details of you?");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtVission.setColumns(20);
        txtVission.setRows(5);
        jScrollPane4.setViewportView(txtVission);

        jXLabel3.setText("What your vision for this union?");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtService.setColumns(20);
        txtService.setRows(5);
        jScrollPane3.setViewportView(txtService);

        txtDesignation.setColumns(20);
        txtDesignation.setRows(5);
        jScrollPane2.setViewportView(txtDesignation);

        jXLabel5.setText("Why you want to this Designation?");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jXLabel2.setText("How will do you services to Students?");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jXButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jXButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/enter.png"))); // NOI18N
        jXButton1.setText("Enter Details");
        jXButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVisibleLayout = new javax.swing.GroupLayout(pnlVisible);
        pnlVisible.setLayout(pnlVisibleLayout);
        pnlVisibleLayout.setHorizontalGroup(
            pnlVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisibleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVisibleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisibleLayout.createSequentialGroup()
                        .addGroup(pnlVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlVisibleLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(pnlVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))
                    .addGroup(pnlVisibleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisibleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );
        pnlVisibleLayout.setVerticalGroup(
            pnlVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisibleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVisibleLayout.createSequentialGroup()
                        .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVisibleLayout.createSequentialGroup()
                        .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jXPanel1.add(pnlVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 920, 310));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/update.png"))); // NOI18N
        jButton1.setText("Upload Details");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jXPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 240, 40));

        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1050, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            pnlVisible.setVisible(true);
//            String index=txtIndex.getText();
//            System.out.println("index"+index);
//            CandidateDTO candidateDTO=CandidateController.searchCandidate(index);
//            String pwrd=candidateDTO.getPassword();
//            System.out.println("pw"+pwrd);
//            String password=txtPwrd.getText();
//            if(pwrd.equals(password)){
//                pnlVisible.setVisible(true);
//            }
        } catch (Exception ex) {
            Logger.getLogger(UploadCandidate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        try {
            String designation=txtDesignation.getText();
            String service=txtService.getText();
            String vision=txtVission.getText();
            String other=txtDetail.getText();
            String indexNo=txtIndex.getText();
            CandidateDTO candidateDTO=new CandidateDTO(indexNo,designation,service,vision,other);
            boolean update=CandidateController.updateCandidate(candidateDTO);
            if(update){
                JOptionPane.showMessageDialog(this,"Updated...");
            }else{
                JOptionPane.showMessageDialog(this,"Update Failled");
            }
        } catch (Exception ex) {
            Logger.getLogger(UploadCandidate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private javax.swing.JPanel pnlVisible;
    private org.jdesktop.swingx.JXTextArea txtDesignation;
    private org.jdesktop.swingx.JXTextArea txtDetail;
    private org.jdesktop.swingx.JXTextField txtIndex;
    private javax.swing.JPasswordField txtPwrd;
    private org.jdesktop.swingx.JXTextArea txtService;
    private org.jdesktop.swingx.JXTextArea txtVission;
    // End of variables declaration//GEN-END:variables
}
