/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.votingsystem.view;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import lk.ijse.votingsystem.controller.CommissionController;
import lk.ijse.votingsystem.dto.CommissionDTO;
import org.jdesktop.swingx.JXPanel;

/**
 *
 * @author HP
 */
public class ViewCommissioner extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCommissioner
     */
    private JPanel pnlSet;
    public ViewCommissioner() {
        initComponents();
        loadAllCommissioner();
    }

    ViewCommissioner(JPanel pnlView) {
        initComponents();
        loadAllCommissioner();
        pnlSet=pnlView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCommissioner = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("All Commissioners");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 471, 54));

        tblCommissioner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Commissioner ID", "Commissioner Name", "Commissioner NIC", "Address", "Telephone No."
            }
        ));
        jScrollPane1.setViewportView(tblCommissioner);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 760, 260));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/votingsystem/image/Back.png"))); // NOI18N
        jLabel3.setText("Back");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, 50));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 990, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        ManageCommission manageCommission=new ManageCommission((JXPanel) pnlSet);
        pnlSet.removeAll();
        pnlSet.add(manageCommission);
        manageCommission.setVisible(true);
    }//GEN-LAST:event_jLabel3MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCommissioner;
    // End of variables declaration//GEN-END:variables

    private void loadAllCommissioner() {
        try {
            System.out.println("Method Running");
            DefaultTableModel dtm = (DefaultTableModel) tblCommissioner.getModel();
            List<CommissionDTO> commioners = CommissionController.getAllMembers();
            System.out.println("list"+commioners);
            if (commioners == null) {
                System.out.println("null");
                return;
            } else {
                for (CommissionDTO commioner : commioners) {
                   
                    Object[] rowData = {commioner.getCmId(), commioner.getName(), commioner.getNic(), commioner.getAddress(), commioner.getTpNo()};
                    dtm.addRow(rowData);
                    System.out.println("for-each running");
                }
                System.out.println("commission running");
            }
//            for (CommissionDTO commioner : commioners) {
//                System.out.println("for-each runnning");
//                Object[] rowData={commioner.getCmId(),commioner.getName(),commioner.getNic(),commioner.getAddress(),commioner.getTpNo()};
//                System.out.println("cmiD"+commioner.getCmId());
//                dtm.addRow(rowData);
//            }
//        
        } catch (Exception ex) {
            Logger.getLogger(ViewCommissioner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
