
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.votingsystem.view;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.votingsystem.controller.ElectionController;
import lk.ijse.votingsystem.dto.ElectionDetailDTO;

/**
 *
 * @author HP
 */
public class voteDetail extends javax.swing.JInternalFrame {

    /**
     * Creates new form voteDetail
     */
    public voteDetail() {
        initComponents();
        //getDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        txtIndroduction = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        txtVenue = new org.jdesktop.swingx.JXTextField();
        txtEndTime = new org.jdesktop.swingx.JXTextField();
        txtStartTime = new org.jdesktop.swingx.JXTextField();
        txtEleDate = new org.jdesktop.swingx.JXTextField();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setText("Election Details");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jXPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 483, 78));

        txtIndroduction.setText("introduction");
        jXPanel1.add(txtIndroduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 787, 150));

        jXLabel3.setText("Election Date");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 112, 32));

        jXLabel4.setText("Venue");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 112, 32));

        jXLabel5.setText("Starting Time");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 112, 32));

        jXLabel7.setText("Ending Time");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 112, 32));

        txtVenue.setEnabled(false);
        txtVenue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(txtVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 330, 30));

        txtEndTime.setEnabled(false);
        txtEndTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(txtEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 140, 30));

        txtStartTime.setEnabled(false);
        txtStartTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(txtStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 140, 30));

        txtEleDate.setEnabled(false);
        txtEleDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(txtEleDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 140, 30));

        jXLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXLabel8.setEnabled(false);
        jXLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1030, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXTextField txtEleDate;
    private org.jdesktop.swingx.JXTextField txtEndTime;
    private org.jdesktop.swingx.JXLabel txtIndroduction;
    private org.jdesktop.swingx.JXTextField txtStartTime;
    private org.jdesktop.swingx.JXTextField txtVenue;
    // End of variables declaration//GEN-END:variables

    private void getDetail(){
        try {
            List<ElectionDetailDTO> electionList=ElectionController.getAll();
            for (ElectionDetailDTO electionDetailDTO : electionList) {
                txtIndroduction.setText(electionDetailDTO.getDescription());
                txtEleDate.setText(electionDetailDTO.getElectionDate());
                txtStartTime.setText(electionDetailDTO.getStartTime());
                txtEndTime.setText(electionDetailDTO.getEndTime());
                txtVenue.setText(electionDetailDTO.getPlace());
            }
        } catch (Exception ex) {
            Logger.getLogger(voteDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
